config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)
  get 'profiles/show'
  get 'profiles/edit'
  get 'sessions/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root 'pages#index'
  root 'festivals#index'
  
  resources :users
  resources :topics do
    resources :comments
  end
  resources :festivals

  get '/login',  to: 'sessions#new'
  post '/login',  to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  get 'favorites/index'
  post '/favorites', to: 'favorites#create'
  delete '/favorites', to: 'favorites#destroy'
  
  get 'gones/index'
  post '/gones', to: 'gones#create'
  delete '/gones', to: 'gones#destroy'
  
  get 'wantgos/index'
  post '/wantgos', to: 'wantgos#create'
  delete '/wantgos', to: 'wantgos#destroy'
  
  get 'festivals/index', to: 'festivals#path'
  get 'festivals/:id', to: 'festivals#show'
  
  resource :profile, only: %i[show edit update]
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :topic
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :topic
end

app/models/festival.rb
class Festival < ApplicationRecord
  has_many :topics
  has_many :gones
  
  mount_uploader :logo, ImageUploader
  
  has_many :gones
  has_many :gone_users, through: :gones, source: 'user'
  has_many :wantgos
  has_many :wantgo_users, through: :wantgos, source: 'user'
  
end

app/models/gone.rb
class Gone < ApplicationRecord
  belongs_to :user
  belongs_to :festival
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :user_id, presence: true
  validates :body, presence: true
  validates :image, presence: true
  
  mount_uploader :image, ImageUploader
  
  belongs_to :user
  belongs_to :festival
  has_many :favorites
  has_many :favorite_users, through: :favorites, source: 'user'
  has_many :comments
  
  #def user
    #インスタンスメソッド内でselfはインスタンス自身を指す。
    #return Topic.find_by(id: self.id)
  #end
  
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { minimum: 1, maximum: 15 }
  
  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[A-Z])(?=.*?\d)(?=.*?[\W_])[!-~]{8,}+\z/
  validates :password, presence: true, format: { with: VALID_PASSWORD_REGEX }, length: { minimum: 8, maximum: 24 }
  
  has_secure_password
  
  has_many :topics
  has_many :favorites
  has_many :favorite_topics, through: :favorites, source: 'topic'
  has_many :gones
  has_many :gone_festivals, through: :gones, source: 'festival'
  has_many :wantgos
  has_many :wantgo_festivals, through: :wantgos, source: 'festival'
  has_many :festivals
  has_many :comments
  
  #authenticates_with_sorcery!
  mount_uploader :avatar, AvatarUploader
  

end

app/models/wantgo.rb
class Wantgo < ApplicationRecord
  belongs_to :user
  belongs_to :festival 
end

app/controllers/gones_controller.rb
class GonesController < ApplicationController
  def index
    @gone_festivals = current_user.gone_festivals
  end
  
  def create
    gone = Gone.new
    gone.user_id = current_user.id
    gone.festival_id = params[:festival_id]

    if gone.save
      redirect_to festivals_path, success: '行った！'
    else
      redirect_to festivals_path, danger: '登録に失敗しました'
    end
  end
  
  def destroy
    @gone = Gone.find_by(user_id: current_user.id, festival_id: params[:festival_id])
    @gone.destroy
    redirect_to festivals_path, success: 'お気に入りを取り消しました'
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_admin_user!
  
  def index
    @users = User.page(params[:page]).per(3).reverse_order
  end
  
  def show
    @user = User.find(params[:id])
    @topics = current_user.topics.all.order("created_at DESC")
  end
  
  def new
    @user = User.new
  end
  
  def create
    #binding.pry
    @user = User.new(user_params)
    if @user.save
      flash[:info] = '登録が完了しました'
      redirect_to root_path
    else
      flash.now[:danger] = '登録に失敗しました'
      render :new
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    #binding.pry
    @user.update(user_params)
    if @user.save
      redirect_to user_path, success: 'ユーザー情報を更新しました'
    else
      flash.now[:danger] = 'ユーザー情報を更新できませんでした'
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :gender, :address, :self_introduction, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/festivals_helper.rb
module FestivalsHelper
end

app/helpers/gones_helper.rb
module GonesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def signed_in?
    !current_user.nil?
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/wantgos_helper.rb
module WantgosHelper
end

app/views/users/edit.html.erb
<%# provide(:title, "Edit user") %>
<div class="cover-user-edit">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-3 col-md-6">
        <div class="top-index-single">
          <div class="text-white">
            <h1>Update your profile</h1>
            <%= form_with(model: @user, local: true) do |f| %>
              <%#= render 'shared/error_messages' %>
              <div class="form-group">
                <%= f.label :name %>
                <%= f.text_field :name, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :email %>
                <%= f.email_field :email, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :password %>
                <%= f.password_field :password, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :password_confirmation, "Confirmation" %>
                <%= f.password_field :password_confirmation, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%#= f.label :gender, '性別' %>
                <%#= f.select :gender, {'男性': 1, '女性': 2, '未回答': 3}, { include_blank: '選択してください'}, { class: 'form-control' , required: true } %>
              </div>
              <div class="form-group">
                <%= f.label :address %>
                <%= f.text_field :address, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :self_introduction %>
                <%= f.text_field :self_introduction, class: 'form-control' %>
              </div>
              <%= f.submit "更新", class: "btn btn-primary" %>
            <% end %>
          </div>
          <div class="gravatar_edit">
            <%#= gravatar_for @user %>
            <a href="http://gravatar.com/emails" target="_blank">change</a>
          </div>
          <form method="post">
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h1 class="text-center text-white">Sign up</h1>
        <%= form_for @user do |f| %>
          <div class="form-group">
            <%= f.label :name, class: 'text-white' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :email, class: 'text-white' %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password, class: 'text-white'%>
            <%= f.password_field :password, class: 'form-control'%>
            <p class="conditional-character">※半角英数字　大文字＆小文字＆数字＆記号1文字以上必須</p>
          </div>
          <div class="form-group">
            <%= f.label :password_confirmation, class: 'text-white'%>
            <%= f.password_field :password_confirmation, class: 'form-control'%>
            <p class="conditional-character">※確認用パスワード入力</p>
          </div>
          
          <%= f.submit "登録" , class: 'btn-block btn-white' %>
        <% end %>
        <%= link_to 'ログインはこちら', login_path, class: 'text_white' %>
      </div>
    </div>
  </div>
  
</div>

app/views/users/show.html.erb
<div class="cover-user-show">
  <div class="container">
    <div class="users-new-container">
      <% if logged_in? && @user == current_user %>
      <h1 class="text-center text-white">マイページ</h1>
      <% else %>
      <h1 class="text-center text-white"><%= @user.name %>さんのページ</h1>
      <% end %>
    </div>

    <div class="row users-new-container">
      <div class="row">
        <div class="col-md-offset-1 col-md-4">
          <div class="user-profile text-white">
            <% if @user.avatar? %>
              <%= image_tag @user.avatar.url %>
            <% else %>
              <i class="fa-solid fa-circle-user fa-10x"></i>
            <% end %>
            <h3>名前： <%= @user.name %></h2>
            <h3><%#= @user.gender %></h3>
            <h3>住まい：<%= @user.address %></h3>
            <h3>一言： <%= @user.self_introduction %></h3>
            <%= link_to '編集', edit_user_path, class: 'btn btn-success float-right' %>
          </div>
        </div>
        <div class="col-md-5">
          <div class="users-new-container topic-index-single">
            <%= link_to '新規に投稿する', new_topic_path, class: "btn btn-white btn-show-block" %>
            <%# if current_user.id == @topic.user_id %>
            <div class="topic-author user-page">
              <% @topics.each do |topic| %>
                <p><%= image_tag topic.image.url, size: "560x360" %></p>
                <p class="text-white imag" ><%= topic.body %></p>
                <span class="text-white">
                  <%= topic.created_at %>
                </span>
                <div class="text-white" >
                  <span><%#= image_tag '#' %></span>
                  <ul class="text-white" >
                    <li>
                      <%= link_to '削除する', topic_path(topic.id), method: :delete %>
                    </li>
                  </ul>
                </div> 
              <% end %>
            <%# end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>