config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)
  get 'profiles/show'
  get 'profiles/edit'
  get 'sessions/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root 'pages#index'
  root 'festivals#index'
  
  resources :users
  resources :topics do
    resources :comments
  end
  resources :festivals

  get '/login',  to: 'sessions#new'
  post '/login',  to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  get 'favorites/index'
  post '/favorites', to: 'favorites#create'
  delete '/favorites', to: 'favorites#destroy'
  
  get 'gones/index'
  post '/gones', to: 'gones#create'
  delete '/gones', to: 'gones#destroy'
  
  get 'wantgos/index'
  post '/wantgos', to: 'wantgos#create'
  delete '/wantgos', to: 'wantgos#destroy'
  
  get 'festivals/index', to: 'festivals#path'
  get 'festivals/:id', to: 'festivals#show'
  
  resource :profile, only: %i[show edit update]
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :topic
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :topic
end

app/models/festival.rb
class Festival < ApplicationRecord
  has_many :topics
  has_many :gones
  
  mount_uploader :logo, ImageUploader
  
  has_many :gones
  has_many :gone_users, through: :gones, source: 'user'
  has_many :wantgos
  has_many :wantgo_users, through: :wantgos, source: 'user'
  
end

app/models/gone.rb
class Gone < ApplicationRecord
  belongs_to :user
  belongs_to :festival
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :user_id, presence: true
  validates :body, presence: true
  validates :image, presence: true
  
  mount_uploader :image, ImageUploader
  
  belongs_to :user
  belongs_to :festival
  has_many :favorites
  has_many :favorite_users, through: :favorites, source: 'user'
  has_many :comments
  
  #def user
    #インスタンスメソッド内でselfはインスタンス自身を指す。
    #return Topic.find_by(id: self.id)
  #end
  
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { minimum: 1, maximum: 15 }
  
  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[A-Z])(?=.*?\d)(?=.*?[\W_])[!-~]{8,}+\z/
  validates :password, presence: true, format: { with: VALID_PASSWORD_REGEX }, length: { minimum: 8, maximum: 24 }
  
  has_secure_password
  
  has_many :topics
  has_many :favorites
  has_many :favorite_topics, through: :favorites, source: 'topic'
  has_many :gones
  has_many :gone_festivals, through: :gones, source: 'festival'
  has_many :wantgos
  has_many :wantgo_festivals, through: :wantgos, source: 'festival'
  has_many :festivals
  has_many :comments
  
  #authenticates_with_sorcery!
  mount_uploader :avatar, AvatarUploader
  

end

app/models/wantgo.rb
class Wantgo < ApplicationRecord
  belongs_to :user
  belongs_to :festival 
end

app/controllers/festivals_controller.rb
class FestivalsController < ApplicationController
  def new
    @festival = Festival.new
  end
  
  def create
    @festival = Festival.new(festival_params)
    
    if @festival.save
      redirect_to festival_path(:id), success: '投稿に成功しました'
    else
      flash.now[:danger] = "投稿に失敗しました"
      render :new
    end
  end
  
  def index
    @festivals = Festival.all.includes(:gone_users)
    @festivals = Festival.all.includes(:wantgo_users)
  end
  
  def show
    @festival = Festival.find(params[:id])
    @festival_topics = @festival.topics.order(created_at: :desc)
    @comment = Comment.new
  end
  
  def comment
    @comment = Comment.new(body: params[:body], topic_id: params[:topic_id], user_id: params[:user_id])
    @comment.save
    redirect_to topics_path
  end
  
  private
  def festival_params
    params.require(:festival).permit(:event, :place, :ditail, :logo, :homepage)
  end
end

app/controllers/gones_controller.rb
class GonesController < ApplicationController
  def index
    @gone_festivals = current_user.gone_festivals
  end
  
  def create
    gone = Gone.new
    gone.user_id = current_user.id
    gone.festival_id = params[:festival_id]

    if gone.save
      redirect_to festivals_path, success: '行った！'
    else
      redirect_to festivals_path, danger: '登録に失敗しました'
    end
  end
  
  def destroy
    @gone = Gone.find_by(user_id: current_user.id, festival_id: params[:festival_id])
    @gone.destroy
    redirect_to festivals_path, success: 'お気に入りを取り消しました'
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_admin_user!
  
  def index
    @users = User.page(params[:page]).per(3).reverse_order
  end
  
  def show
    @user = User.find(params[:id])
    @topics = current_user.topics.all.order("created_at DESC")
  end
  
  def new
    @user = User.new
  end
  
  def create
    #binding.pry
    @user = User.new(user_params)
    if @user.save
      flash[:info] = '登録が完了しました'
      redirect_to root_path
    else
      flash.now[:danger] = '登録に失敗しました'
      render :new
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    #binding.pry
    @user.update(user_params)
    if @user.save
      redirect_to user_path, success: 'ユーザー情報を更新しました'
    else
      flash.now[:danger] = 'ユーザー情報を更新できませんでした'
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :gender, :address, :self_introduction, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/festivals_helper.rb
module FestivalsHelper
end

app/helpers/gones_helper.rb
module GonesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def signed_in?
    !current_user.nil?
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/wantgos_helper.rb
module WantgosHelper
end

app/views/festivals/index.html.erb
<body>
  <div class="top-index-wrapper" id="slide">
    <div class="container">
      <div class="top-index-container text-center">
        <h1 class="top-title text-white">No MusicFestival No Life？</h1>
        <h3 class="top-body">日本全国で開催されている音楽フェスの思い出を共有しよう</h2>
      </div>
      <div class="row row-eq-height">
        <% @festivals.each do |fes| %>
        <div class="col-md-4">
          <div class="top-index-single">
            <h2 class="top-author">
              <% if fes.logo.present? %>
                <%= link_to festival_path(id: fes.id) do %>
                  <%= image_tag fes.logo.url %>
                <% end %>
              <% end %>
              <%= fes.event %>
            </h2>
            <h3 class="top-event-place"><i class="fa-solid fa-location-dot"></i>
              <%= fes.place %>
            </h3>
            <p class="top-event-text">
              <%= fes.ditail %>
            </p>
            <p class="top-event-text">
              <%= link_to '公式ホームページ', fes.homepage %>
            </p>
            <div>
              <div class="icon">
                <% if !fes.gone_users.include?(current_user) %>
                  <%= link_to gones_path(festival_id: fes.id), method: :post do %>
                    <div><i class="fa-solid fa-person-running fa-3x top-index-icon" style="color:#808080;"></i>
                      <%= fes.gone_users.count %>
                    </div>
                    <p class="icon-description" style="color:#808080;">行った！</p>
                  <% end %>
                <% else %>
                  <%= link_to gones_path(festival_id: fes.id), method: :delete do %>
                    <i class="fa-solid fa-person-running fa-3x top-index-icon" style="color:#0000ff;"></i>
                      <%= fes.gone_users.count %>
                    <p class="icon-description" style="color:#0000ff;">行った！</p>
                  <% end %>
                <% end %>
              </div>
              <div class="icon">
                <% if !fes.wantgo_users.include?(current_user) %>
                  <%= link_to wantgos_path(festival_id: fes.id), method: :post do %>
                    <i class="fa-regular fa-face-smile fa-3x top-index-icon" style="color:#808080;"></i>
                      <span><%= fes.wantgo_users.count %></span>
                    <p class="icon-description" style="color:#808080;">行きたい</p>
                  <% end %>
                <% else%>
                  <%= link_to wantgos_path(festival_id: fes.id), method: :delete do %>
                    <i class="fa-regular fa-face-smile fa-3x top-index-icon" style="color:#ff8c00;"></i>
                      <span><%= fes.wantgo_users.count %></span>
                    <p class="icon-description" style="color:#ff8c00;">行きたい</p>
                  <% end %>
                <% end %>
              </div>
              <div class="icon">
                <%= link_to new_topic_path(festival_id: fes.id) do %>
                  <i class="fa-solid fa-file-pen fa-3x top-index-icon-comment" style="color:#808080;"></i>
                  <span><%#= fes.comment_users.count %></span>
                  <p class="icon-description comment" style="color:#808080;">投稿する</p>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
  
  <script>
    $(function() {
      var i = 1;
      setInterval(function() {
        if(i > 5) i = 1;
        $("#slide").css("background-image","url('/assets/background/img"+i+".jpg')");
        i++;
        }, 10000
      );
    });
  </script>
</body>

app/views/festivals/new.html.erb
<div class="topic-new-wrapper" >
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Festival</h1>
        <%= form_for @festival do |f| %>
          <div class="form-group">
            <%= f.label :event %>
            <%= f.text_area :event, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :place %>
            <%= f.text_area :place, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :ditail %>
            <%= f.text_area :ditail, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :logo %>
            <%= f.file_field :logo%>
          </div>

          <%= f.submit '登録', class: 'btn btn-black btn-block' %>

        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/festivals/show.html.erb
<div class="top-index-wrapper">
  <div class="container">
      <div class="row">
        <div class="col-md-offset-1 col-md-4">
          <div class="top-index-single">
            <h2 class="top-author">
              <%= image_tag @festival.logo.url %>
            </h2>
            <h3 class="top-event-place"><i class="fa-solid fa-location-dot"></i>
              <%= @festival.place %>
            </h3>
            <p class="top-event-text">
              <p><%= link_to '公式ホームページ', @festival.homepage %></p>
              <p><%= @festival.ditail %></p>
            </p>
          </div>
        </div>
        
        <div class="col-md-6">
          <div class="top-index-single">
            <h2 class="top-author">
              <i class="fa-solid fa-play top-title"> <%= @festival.event %> 投稿一覧ページ</i>
              <h3 class="text-center">新規投稿順</h3>
            </h2>
            
            <div>
              <% @festival_topics.each do |topic| %>
               <div class="row">
                 <div class="col-md-6">
                   <div class="topic-show-single">
                     <h2 class="topic-author">
                       <p><%= topic.user.name %> さんの投稿</p>
                     </h2>
                     <%= image_tag topic.image.url %>
                     <% if !topic.favorite_users.include?(current_user) %>
                       <%= link_to favorites_path(topic_id: topic.id), method: :post do %>
                         <i class="fa-solid fa-thumbs-up fa-2x like-btn" ></i>
                       <% end %>
                     <% else %>
                       <%= link_to favorites_path(topic_id: topic.id), method: :delete do %>
                         <i class="fa-solid fa-thumbs-up fa-2x unlike-btn"></i>
                       <% end %>
                     <% end %>
                     <%= topic.favorite_users.count %>
                     <p class="topic-text">
                       <%= topic.body %>
                     </p>
                     <%= form_for [topic, @comment] do |f| %>
                       <div class="form-group">
                         <%= f.text_area :body, class: 'form-control'%>
                       </div>
                       <%= hidden_field :id, :value => topic.id %>
                       <button type="submit" class="btn btn-primary">コメント</button>
                     <% end %>
                     <% topic.comments.each do |comment| %>
                       <%# topic.comment %>
                       <p><%= comment.body %></p>
                     <% end %>
                   </div>
                 </div>
               </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
  </div>
</div>