config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)
  get 'profiles/show'
  get 'profiles/edit'
  get 'sessions/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #root 'pages#index'
  root 'festivals#index'
  
  resources :users
  resources :topics do
    resources :comments
  end
  resources :festivals

  get '/login',  to: 'sessions#new'
  post '/login',  to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  get 'favorites/index'
  post '/favorites', to: 'favorites#create'
  delete '/favorites', to: 'favorites#destroy'
  
  get 'gones/index'
  post '/gones', to: 'gones#create'
  delete '/gones', to: 'gones#destroy'
  
  get 'wantgos/index'
  post '/wantgos', to: 'wantgos#create'
  delete '/wantgos', to: 'wantgos#destroy'
  
  get 'festivals/index', to: 'festivals#path'
  get 'festivals/:id', to: 'festivals#show'
  
  resource :profile, only: %i[show edit update]
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :topic
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :topic
end

app/models/festival.rb
class Festival < ApplicationRecord
  has_many :topics
  has_many :gones
  
  mount_uploader :logo, ImageUploader
  
  has_many :gones
  has_many :gone_users, through: :gones, source: 'user'
  has_many :wantgos
  has_many :wantgo_users, through: :wantgos, source: 'user'
  
end

app/models/gone.rb
class Gone < ApplicationRecord
  belongs_to :user
  belongs_to :festival
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :user_id, presence: true
  validates :body, presence: true
  validates :image, presence: true
  
  mount_uploader :image, ImageUploader
  
  belongs_to :user
  belongs_to :festival
  has_many :favorites
  has_many :favorite_users, through: :favorites, source: 'user'
  has_many :comments
  
  #def user
    #インスタンスメソッド内でselfはインスタンス自身を指す。
    #return Topic.find_by(id: self.id)
  #end
  
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { minimum: 1, maximum: 15 }
  
  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[A-Z])(?=.*?\d)(?=.*?[\W_])[!-~]{8,}+\z/
  validates :password, presence: true, format: { with: VALID_PASSWORD_REGEX }, length: { minimum: 8, maximum: 24 }
  
  has_secure_password
  
  has_many :topics
  has_many :favorites
  has_many :favorite_topics, through: :favorites, source: 'topic'
  has_many :gones
  has_many :gone_festivals, through: :gones, source: 'festival'
  has_many :wantgos
  has_many :wantgo_festivals, through: :wantgos, source: 'festival'
  has_many :festivals
  has_many :comments
  
  #authenticates_with_sorcery!
  mount_uploader :avatar, AvatarUploader
  

end

app/models/wantgo.rb
class Wantgo < ApplicationRecord
  belongs_to :user
  belongs_to :festival 
end

app/controllers/gones_controller.rb
class GonesController < ApplicationController
  def index
    @gone_festivals = current_user.gone_festivals
  end
  
  def create
    gone = Gone.new
    gone.user_id = current_user.id
    gone.festival_id = params[:festival_id]

    if gone.save
      redirect_to festivals_path, success: '行った！'
    else
      redirect_to festivals_path, danger: '登録に失敗しました'
    end
  end
  
  def destroy
    @gone = Gone.find_by(user_id: current_user.id, festival_id: params[:festival_id])
    @gone.destroy
    redirect_to festivals_path, success: 'お気に入りを取り消しました'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/festivals_helper.rb
module FestivalsHelper
end

app/helpers/gones_helper.rb
module GonesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def signed_in?
    !current_user.nil?
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/wantgos_helper.rb
module WantgosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gogofestival</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet"
          href="https://use.fontawesome.com/releases/v6.4.0/css/all.css">
  </head>
  
  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
    <% end %>
    
    <nav class="navbar navbar-default navbar-fixed-top navbar-transparent">
      <div class="container">
        <%= link_to root_path do %>
          <span><%= image_tag "IMG_6869__1_-removebg-preview.png", class: "navbar-brand" %></span>
        <% end %>
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li>
              <%= link_to user_path(current_user.id) do %>
                <i class="fa-solid fa-user fa-3x" aria-hidden="true" ></i>
                <p>My page</p>
              <% end %>
            </li>
            <li>
              <%= link_to favorites_index_path do %>
                <i class="fa-solid fa-thumbs-up fa-3x style="color:#ff4500;""></i>
                <p>good</p>
              <% end %>
            </li>
            <li>
              <%= link_to logout_path, method: :delete do %>
                <i class="fa-solid fa-right-from-bracket fa-3x"></i>
                <p>Log out</p>
              <% end %>
            </li>
          <% else %>
            <li>
              <%= link_to new_user_path do %>
                <i class="fa-solid fa-user-plus fa-3x"></i>
                <p>Sign up</p>
              <% end %>
            </li>

            <li>
              <%= link_to login_path do %>
                <i class="fa-solid fa-right-to-bracket fa-3x"></i>
                <p>Log in</p>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa-solid fa-magnifying-glass fa-3x"></i>
                <p>search</p>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
    
    <%= yield %>
    
    <script>
      $(function(){
        $(".alert").fadeOut(5000);
      });
    </script>
    
  </body>
</html>

app/views/pages/index.html.erb
<div class="top-hero-wrapper text-center">
  <div class="container top-hero-container">
    <h1 class="text-white">Enjoy the Festival</h1>
    <h2 class="text-white">Let's share that excitement!</h2>
    <div class="row">
      <div class="col-md-offset-4 col-md-4 ">
        <%= link_to 'Sign up', new_user_path, class: 'btn btn-block btn-white' %>
      </div>
      <div class="col-md-offset-4 col-md-4 ">
        <%= link_to 'Log in', login_path, class: 'btn btn-block btn-white' %>
      </div>
    </div>
  </div>
</div>